--- #YAML:1.0
name:               Array-Transpose
version:            0.06
abstract:           Transposes a 2-Dimensional Array
author:
    - Michael R. Davis (domain=>stopllc,tld=>com,account=>mdavis)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Exporter:      0
    strict:        0
    Test::Simple:  0.44
    vars:          0
    warnings:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
