--- #YAML:1.0
name:                Array-Transpose
version:             0.05
abstract:            Transposes a 2-Dimensional Array
license:             ~
author:              
    - Michael R. Davis (domain=>stopllc,tld=>com,account=>mdavis)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Exporter:                      0
    strict:                        0
    Test::Simple:                  0.44
    vars:                          0
    warnings:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
